// Code generated by go-bindata.
// sources:
// migrations/1543497171_init.down.sql
// migrations/1543497171_init.up.sql
// DO NOT EDIT!

package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __1543497171_initDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x4a\x2d\x4e\x2d\x29\xb6\xe6\xc2\x2a\x59\x5a\x9c\x5a\x04\x97\x8b\x0c\x40\x97\x8a\x2f\x2e\x49\x2c\x29\x2d\xb6\x56\xe0\x02\x04\x00\x00\xff\xff\x43\x7b\xc7\xbb\x5b\x00\x00\x00")

func _1543497171_initDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1543497171_initDownSql,
		"1543497171_init.down.sql",
	)
}

func _1543497171_initDownSql() (*asset, error) {
	bytes, err := _1543497171_initDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1543497171_init.down.sql", size: 91, mode: os.FileMode(420), modTime: time.Unix(1544874101, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __1543497171_initUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xac\x92\x4d\x8f\xd3\x30\x10\x86\xcf\xe3\x5f\x31\xb7\x36\x55\xa4\x22\x10\x70\xe8\xc9\xb4\x53\xb0\x48\xdd\xe2\x38\xcb\xf6\x14\x99\xda\xb0\x16\xfd\x52\xec\x88\xfd\xf9\x88\x64\x13\x52\x28\xac\x04\x7b\x4d\xde\x77\x34\x7e\x9e\x59\xa8\xf5\x06\xf5\x76\x43\x28\x96\x48\xb7\x22\xd7\x39\xd6\xc1\x55\x65\x88\x26\xd6\x61\xc6\xe6\x8a\xb8\xa6\x36\x32\xf8\x81\x3c\x47\x92\xc5\x0a\xc7\x23\x49\x1f\x47\x29\x8e\x6e\x48\x89\xa5\xa0\xc5\x28\x99\xb1\xbe\xc5\xdf\x64\xcd\x64\xb9\xd6\xc3\xe9\x01\xc7\x0c\xbc\x45\x80\x9c\x94\xe0\x19\x6e\x94\x58\x71\xb5\xc5\xf7\xb4\x4d\x19\x98\xdd\xee\x54\x1f\x63\xe9\x2d\xcc\xdf\x71\x85\xe3\x17\xaf\x12\x2c\xa4\xf8\x50\x50\x33\x49\x16\x59\x96\xe2\x74\x82\x5f\xf6\xa7\x4f\x66\x8f\xde\xba\x63\xf4\x9f\xbd\xab\x70\x32\x65\x0c\xdc\xc1\xf8\x3d\x02\xc0\x0d\x57\xed\x80\x97\xcf\x92\x9f\x4d\x06\x67\x13\xc2\xb7\x53\x65\xcb\x3b\x13\xee\x70\x90\x7b\xfd\xfc\x22\xf7\xf0\x56\x00\x18\x3e\x7d\x10\x88\xa7\xaf\xee\x08\x80\x7f\xdb\x93\x31\x98\x4e\x30\xfa\x83\x0b\xd1\x1c\xce\xe1\xc7\x8e\xb0\xab\x9c\x89\xce\x96\x26\x02\x80\x16\x2b\xca\x35\x5f\x6d\xfa\x16\x2e\x68\xc9\x8b\x4c\xe3\xbc\x50\x8a\xa4\x2e\xfb\x48\xca\xa0\x3e\xdb\x7f\xeb\xb2\x81\x1a\x21\x17\x74\x7b\x4d\x4d\xd9\xd0\x2b\xbd\xbd\xc7\xb5\xec\x6c\x35\xdf\x92\xd9\xe3\xe5\x06\xc8\x2f\xe5\xe6\xdb\x23\x57\x51\xb9\xe0\xe2\xc3\x59\x5c\x3d\x8a\x8e\x75\xaf\xea\x1a\x6b\xc6\x5a\x51\xde\x82\x90\x9a\xde\x92\x42\x45\x4b\x52\x24\xe7\xd4\x5f\x9e\xb7\xc9\x1f\xa4\xb4\xcb\xbb\xfb\xb3\xaf\x5a\xbc\xbf\xc3\x4d\x2f\xd5\xfd\x87\xb9\xa7\x14\xd7\xd2\xbb\x84\xdf\x11\xed\xe8\x7f\x0f\x00\x00\xff\xff\x2c\x07\xef\xbc\xea\x03\x00\x00")

func _1543497171_initUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1543497171_initUpSql,
		"1543497171_init.up.sql",
	)
}

func _1543497171_initUpSql() (*asset, error) {
	bytes, err := _1543497171_initUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1543497171_init.up.sql", size: 1002, mode: os.FileMode(420), modTime: time.Unix(1544968649, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"1543497171_init.down.sql": _1543497171_initDownSql,
	"1543497171_init.up.sql": _1543497171_initUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"1543497171_init.down.sql": &bintree{_1543497171_initDownSql, map[string]*bintree{}},
	"1543497171_init.up.sql": &bintree{_1543497171_initUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

